# Generated by Django 5.1.15 on 2026-03-26 22:24

import apps.labeling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_file',
            field=models.FileField(blank=True, upload_to=apps.labeling.models.task_source_upload_to),
        ),
        migrations.AddField(
            model_name='task',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=16),
        ),
    ]
